service: retaily-server

package:
  patterns:
    - '!.eslintrc.js'
    - '!.nvmrc'
    - '!.prettierrc'
    - '!src/**'
    - '!test/**'
    - '!tsconfig.build.json'
    - '!tsconfig.json'
    - '!docker-compose.yml'
    - '!README.md'

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-west-2
  runtime: nodejs16.x

functions:
  monolith:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
    memorySize: 1024
    timeout: 30
    environment:
      NODE_ENV: ${sls:stage}
