name: CI

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# on:
#   push:
#     branches: [develop]
#   pull_request:
#     branches: [develop]

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"
          cache: "npm"
      - run: npm install -g serverless
      - run: npm ci
      - run: npm run prisma:generate
      - run: npm run build --if-present
      - run: npm run sls:deploy
