name: Deployments (Dev)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  POSTGRES_URL: postgresql://retaily:retailydev@retaily-dev.cosk748dgy0v.us-west-2.rds.amazonaws.com:5432/retaily_db
  JWT_SECRET: 98eef4c0b4c242c8887da70a82c3815b
  BCRYPT_SALT: 12

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"
      - run: npm install -g serverless
      - run: npm ci
      - run: npm run prisma:generate
      - run: npm run build --if-present
      - run: npm run sls:deploy
