name: Deployments (Dev)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  BCRYPT_SALT: ${{ secrets.BCRYPT_SALT }}

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"
      - run: npm install -g serverless
      - run: npm ci
      - run: npm run prisma:generate
      - run: npm run build --if-present
      - run: npm run sls:deploy
